version: "3.3"
services:
  db:
    image: mariadb:latest
    container_name: mysql_web
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database_web
      MYSQL_ROOT_PASSWORD: redhat123
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  web:
    image: php:apache
    container_name: php_web
    ports:
      - "8088:80"
    depends_on: 
      - db
    volumes:
      - /var/www/html:/var/www/html
