version: "2.1"
services:
  db:
    environment:
      - POSTGRES_DB = "db"
      - POSTGRES_PASSWORD = ""
      - POSTGRES_HOST_AUTH_METHOD = "trust"
  image: postgres
  restart: always
  ports:
    - "5432:5432"
  volumes:
    - /opt/database:/var/lib/postgresql/data

  wordpress:
    image: wordpress
    links:
      - db
    ports:
      - "8085:80"
    volumes:
      - ./root/wordpress
    restart: always